insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001001','DCB040','PRECALCULO','2','1','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001002','DCB001','ALGEBRA SUPERIOR','4','1','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001003','TSI001','PENSAMIENTO ALGORITMICO','4','1','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001004','TSI101','HERRAMIENTAS DIGITALES','2','1','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001005','DHI014','PROCESOS DE LECTURA Y ESCRITURA','2','1','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001006','DHE00A','ELECTIVA COMPLEMENTARIA I','2','1','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001007','DCB002','CALCULO DIFERENCIAL ','4','2','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001008','CDB009','MECANICA ','4','2','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001009','TSI203','FUNDAMENTOS DE POO','4','2','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001011','TSI005','ESTRUCTURA DE COMPUTADORES','2','2','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001012','DHE00B','ELECTIVA COMPLEMENTARIA II','2','2','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001013','DCB003','CALCULO INTEGRAL','4','3','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001014','TSI302','PROGRAMACION ORIENTA A OBJETOS','4','3','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001015','TSI301','MOTORES DE BASES DE DATOS','2','3','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001016','TSI303','SISTEMAS OPERATIVOS','2','3','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001017','TSI304','PLANEACION DE SISTEMAS INFORMATICO','4','3','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001018','DHI016','CULTURA FISICA','1','3','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001019','DSB010','ELECTROMAGNETISMO','4','4','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001020','TSI401','PROGRAMACION WEB','4','4','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001021','TSI402','ADMINISTRACION DE SERVIDORES','2','4','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001022','TSI010','SELECCION Y EVALUCION DE TECNOLOGIA','4','4','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001023','TSI000','ELECTIVA DE PROFUNDIZACION I','2','4','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001024','DDI007','INGLES I','2','4','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001025','TSI502','PROGRAMACION EN JAVA','4','5','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001026','TSI503','ESTRUCTURA DE DATOS','2','5','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001027','TSI015','SEGURIDAD DE LAS TECNOLOGIAS DE LA INFORMACION','4','5','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001028','TSI000','ELECTIVA DE PROFUNDIZACION II','2','5','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001029','DDI008','INGLES II','2','5','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001030','DHI017','METODOLOGIA PARA LA ELABORACION DE PROYECTOS I','1','5','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001031','DCB008','CALCULO MULTIVARIABLE','4','6','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001032','DCB011','LABORATORIO DE FISICA','1','6','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001033','TSI600','DESARROLLO DE APLICACIONES EMPRESARIALES','4','6','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001034','FCN030','INTRODUCCION A LA INGENIERIA','2','6','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001035','TSI601','NUEVAS TECNOLOGICAS DE DESARROLLO','4','6','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('001036','TSI000','ELECTIVA DE PROFUNDIZACION III','2','6','A','001');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003001','DCB025','MATEMATICA BASICA','2','1','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003002','FCS001','ADMINISTRACION GENERAL','3','1','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003003','FCS003','ECONOMIA Y EMPRESA','4','1','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003004','TMG101','INTRODUCCION AL MARKETING','4','1','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003005','TMG202','CREATIVIDAD Y DISEÑO','1','1','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003006','DHI014','PROCESO DE LECTURA Y ESCRITURA','2','1','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003007','DCB035','CALCULO','4','2','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003008','FCS006','PROCESOS ADMINISTRATIVOS','4','2','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003009','TMG201','COMPORTAMIENTO DEL CONSUMIDOR','2','2','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003010','TMG303','FUNDAMENTOS DE PUBLICIDAD','2','2','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003011','TMG602','MARKETING AMBIENTAL','2','2','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003012','TMG204','COMUNICACION DE MARKETING','2','2','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003013','FCS010','LEGISLACION EMPRESARIAL','2','2','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003014','DCB004','ESTADISTICA','4','3','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003015','FCS002','CONTABILIDAD GENERAL','4','3','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003016','TMG301','GESTION LOGISTICA Y DISTRIBUCION','2','3','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003017','TMG302','INVESTIGACION DE MERCADOS CUALITATIVA','2','3','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003018','TMG401','EXHIBICION Y MERCHANDISING','2','3','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003019','DHE00A','ELECTIVA COMPLEMENTARIA I','2','3','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003020','DHI016','CULTURA FISICA','1','3','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003021','FCS023','MATEMATICA FINANCIERA','3','4','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003022','TMG402','GESTION DE VENTAS','2','4','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003023','TMG404','LABORATORIO DE DISEÑO PUBLICITARIO','1','4','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003024','TMG405','METODOS Y TIEMPOS','2','4','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003025','DDI007','INGLES I','2','4','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003026','TMG00A','ELECTIVA DE PROFUNDIZACION','4','4','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003027','DHI003','ETICA','2','4','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003028','FCS007','COSTOS Y PRESUPUESTOS','4','5','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003029','TMG501','PLAN DE MARKETING','1','5','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003030','TMG502','HABILIDADES COMERCIALES','1','5','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003031','TMG504','INNOVACION Y DESARROLLO DE PRODUCTOS','2','5','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003032','TMG00B','ELECTIVA DE PROFUNDIZACION','2','5','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003033','DDI008','INGLES II','2','5','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003034','DHI017','METODOLOGIA PARA LA ELABORACION DE PROYECTOS I','1','5','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003035','TMG600','FUNDAMENTOS DE MICROECONOMIA','2','6','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003036','TMG601','FUNDAMENTOS DE COMERCIO INTERNACIONAL','4','6','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003037','TMG403','INTRODUCCION A LOS NEGOCIOS INTERNACIONALES','2','6','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003038','TMG503','ESTRATEGIA DE PRECIO','1','6','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003039','FCS005','ADMINISTRACION DEL TALENTO HUMANO','3','6','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003040','DHE00B','ELECTIVA COMPLEMENTARIA II','2','6','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('003041','TMG00C','ELECTIVA DE PROFUNDIZACION','2','6','A','003');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004001','DCB025','MATEMATICA BASICA','2','1','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004002','TGE100','INTRODUCCION A LA ADMINISTRACION','2','1','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004003','DHI014','PROCESOS DE LECTURA Y ESCRITURA','2','1','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004004','FCS002','CONTABILIDAD GENERAL','4','1','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004005','FCS003','ECONOMIA Y EMPRESA','4','1','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004006','DC8035','CALCULO','4','2','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004007','FCS004','FUNDAMENTOS DE MARKETING','4','2','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004008','TGE200','COSTOS','3','2','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004009','FCS001','ADMINISTRACION GENERAL','3','2','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004010','FCS010','LEGISLACION EMPRESARIAL','2','2','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004011','TGE201','POLITICA ECONOMICA','4','2','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004012','DHB16','CULTURA FISICA','1','3','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004013','DHT000','ELECTIVA COMPLEMENTARIA I','2','3','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004014','TGE300','FUNDAMENTOS DE PRESUPUESTOS','2','3','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004015','FCS012','ADMINISTRACION COMERCIAL Y DE SERVICIOS','4','3','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004016','TGE301','PLANEACION Y CONTROL','4','3','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004017','TGE303','DESARROLLO EMPRESARIAL','2','3','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004018','TCE302','ESTADOS FINANCIEROS','2','3','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004019','FCS023','MATEMATICA FINANCIERA','3','4','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004020','TGE402','ORGANIZACION Y DIRECCION','4','4','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004021','TGE000','ELECTIVA DE PROFUNDIZACION','2','4','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004022','TGE401','GESTION FINANCIERA','2','4','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004023','TGE403','DESARROLLO LOCAL','2','4','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004024','TGE202','TALLER EMPRESARIAL','1','4','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004025','DDI009','INGLES I ','2','4','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004026','DCB004','ESTADISTICA','4','5','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004027','FCS005','ADMINISTRACION DEL TALENTO HUMANO','3','5','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004028','TGE000','ELECTIVA DE PROFUNDIZACION','4','5','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004029','FCS008','ADMINISTRACION DE LA PRODUCCION','4','5','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004030','TGE502','NEGOCIOS INTERNACIONALES','2','5','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004031','DHI017','METODOLOGIA PARA LA ELABORACION DE PROYECTOS I','1','5','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004032','DDI010','INGLES II','2','5','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004033','TGE803','GESTIONES ADMIRATIVAS','2','6','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004034','TGE000','ELECTIVA DE PROFUNDIZACION','4','6','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004035','FCS008','FORMULACION Y EVALUACION DE PROYECTOS','2','6','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004036','DHT000','ELECTIVA DE COMPLEMENTACION III','2','6','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004037','TGE600','INNOVACION EMPRESARIAL','2','6','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004038','DHI003','ETICA','2','6','A','004');
insert into materias (id_materia, nomenclatura, nombre, ponderacion, semestre, estado, id_programa) values('004039','TGE602','SIMULACION EMPRESARIAL','2','6','A','004');
